server:
  port: 7002
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true #false表示不向注册中心注册自己。 推荐  --集群演示改成true
    fetch-registry: true #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7003/eureka/        #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
    #server:
    #enable-self-preservation: false #禁用自我保护模式
spring:
  application:
    name: microservicecloud-eureka